# 提供基础服务
version: "3.5"

services:
  mysql:
    image: mysql:8.0.22
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - srv_provider
    environment:
      MYSQL_ROOT_PASSWORD: azusa520
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - srv_provider
    volumes:
      - /az/redis/config:/docker/config
      - /az/redis/data:/data
    command: redis-server /docker/config/redis.conf

  rmqnamesrv:
    image: foxiswho/rocketmq:server
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - /az/rocketmq/namesrv/data/logs:/opt/logs
      - /az/rocketmq/namesrv/data/store:/opt/store
    networks:
      - srv_provider

  rmqbroker:
    image: foxiswho/rocketmq:broker
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - /az/rocketmq/broker/logs:/opt/logs
      - /az/rocketmq/broker/store:/opt/store
      - /az/rocketmq/broker/conf/broker.conf:/etc/rocketmq/broker.conf
    environment:
      NAMESRV_ADDR: "rmqnamesrv:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms256m -Xmx256m -Xmn256m"
    command: mqbroker -c /etc/rocketmq/broker.conf
    depends_on:
      - rmqnamesrv
    networks:
      - srv_provider

  rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - 8080:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rmqnamesrv
    networks:
      - srv_provider

networks:
  srv_provider:
    external: true
    driver: bridge
